---
title: "Ellena Girma"
description: |
    My name is Ellena Girma, and I am a data analyst intern at CIAT Arusha. I will be using this blog as a tool to share what I have learned in my time at CIAT. This blog will also be a resource for my colleagues who want to learn how to use R for plant breeding.
links: 
  - label: LinkedIn
    url: "https://www.linkedin.com/in/ellena-girma-90a42719b/"
  - label: Github
    url: "https://github.com/e-girma"
  - label: Portfolio
    url: ""
output: 
  postcards::trestles
---


### My Background 

I graduated from La Salle University in Philadelphia in 2021 with a B.S. in Integrated Science Business & Technology (ISBT). Being an ISBT major taught me to view my skillset as a toolbox and use various tools from different fields to solve a problem. As I discovered more skills to add to my toolbox, I found data visualization. I was immediately interested in learning how to visualize and share scientific work in a clear & concise manner. In exploring data viz, I made my way into the broader field of data science and analytics. After graduation, I became a data analyst intern at The International Center for Tropical Agriculture(CIAT) in Arusha, Tanzania. In this role, I primarily work on projects that deal with agrobiodiversity for the common bean. 

